### ISSUE TITLE
Explaining how to build this repository

### ISSUE THREAD

**Issue by horatiusMMXIV** [atomix/catalogue#16]
Hello,

Can you put in the readme how to build the the raftclient and raftserver jars?  I eventually figured out what Maven was and how to build with it but others might find that useful.  

Steps I did to build:
Downloaded maven
Cloned this repo to my computer
cd'd into the root directory of this repo
ran 'mvn clean install'

This appeared to create the two client/server jars.

Are these the correct steps for the command line to build this project?

**Comment by kuujo** [comment]
Yes they are. I'll add the steps to the README

**Comment by kuujo** [comment]
Fixed. Thanks!

**Comment by horatiusMMXIV** [comment]
Awesome!  Thanks a lot!
